name: blendberry_flutter_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  http: ^1.6.0
  meta: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
