name: blendberry_flutter_sdk
description: A completely abstract and configurable Flutter SDK for managing remote configurations. Works with any backend - you implement the interfaces to match your backend's API.
version: 1.0.0
homepage: https://github.com/blendberry/blendberry-flutter-sdk
repository: https://github.com/blendberry/blendberry-flutter-sdk
issue_tracker: https://github.com/blendberry/blendberry-flutter-sdk/issues

environment:
  sdk: ^3.6.1

dependencies:
  meta: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
